[env:esp32-c3-devkitm-1] ;define el entorno de trabajo para el chip
platform = espressif32  ;Descarga el conjunto de herramientas   
board = esp32-c3-devkitm-1  ;Perfil de la placa (pines y memoria)
framework = arduino ;Librerias
monitor_speed = 115200  ; Velocidad de la consola en baudios
build_flags = 
	-D ARDUINO_USB_MODE=1   ;Indica que el USB funciona en modo hardware
	-D ARDUINO_USB_CDC_ON_BOOT=1    ;Redirige el Serial a la consola de la PC apenas arranca
                                    ; Sin esto, verías la consola vacía.